
 - name: set apt repository key for mongodb
   sudo: yes
   apt_key: url=http://keyserver.ubuntu.com id=7F0CEB10 state=present

 - name: set apt repository for mongodb
   apt_repository: repo='deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main' state=present
   notify: apt update
